application: gu-film-experiments

version: 16
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /api/.*
  script: api.app
- url: /reports/.*
  script: report_pages.app
- url: /components/.*
  script: components.app
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on  